### ISSUE TITLE
Table dump

### ISSUE THREAD

**Issue by flozzone** [martflu/aurora#500]
Elaboration_elaboration and auth_user tables would be needed.

**Comment by bobschi** [comment]
Is this a mistake, or will @queltos really be taking care of this? I'm happy if he is.

**Comment by queltos** [comment]
Haha. I will if it's necessary. But for now I'll just forward this torch to Mr Bobschi :)

**Comment by flozzone** [comment]
it was assigned to queltos for mentioning the relevant tables.

**Comment by flozzone** [comment]
Tabledump received. Closing.
