### ISSUE TITLE
near "WITH": syntax error

### ISSUE THREAD

**Issue by tobotron** [martflu/aurora#623]
current master branch requires sqlite 3.8.3 and ubuntu 14.04 (due to changes in queries using 'WITH-syntax')

**Comment by flozzone** [comment]
This is true and ubuntu 14.04 delivers sqlite 3.8.2 while the 'WITH' clause has been introduced in 3.8.3.

But since we are using postgres on the vagrant machine, sqlite is not relevant there. So please use postgres if your don't have a sqlite 3.8.3>=.
